spring:
  profiles:
    active: dev


---
server:
  port: 8085
spring:
  application:
    name: springcloud-provide
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://demo-eureka-7001:7001/eureka/,http://demo-eureka-7002:7002/eureka/,http://demo-eureka-7003:7003/eureka/

MyName:
  name: yiyandingzhen

---
server:
  port: 8086
spring:
  application:
    name: springcloud-provide
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://demo-eureka-7001:7001/eureka/,http://demo-eureka-7002:7002/eureka/,http://demo-eureka-7003:7003/eureka/




