spring:
  profiles:
    active: dev


---
server:
  port: 8085
spring:
  application:
    name: springcloud-provide
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: yiyandingzhen

---
server:
  port: 8086
spring:
  application:
    name: springcloud-provide
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: 22222222




